# Generated by Django 4.1.2 on 2023-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultsmodel",
            name="Import_row_id",
        ),
        migrations.AddField(
            model_name="importsource",
            name="Deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
