# Generated by Django 4.2.1 on 2023-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_remove_resultsmodel_import_row_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="minimum_access_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("00_disabled", "Disabled"),
                    ("10_readonly", "Read-only"),
                    ("20_contributor", "Contributor"),
                    ("30_administrator", "Administrator"),
                    ("40_superuser", "Superuser"),
                ],
                help_text="Only visible to users equal to or above the chosen access level",
                max_length=30,
                null=True,
            ),
        ),
    ]
