# Generated by Django 4.1.2 on 2023-02-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_importsource_delete_isapproved_false_results_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importsource',
            options={'verbose_name': 'Imported Datasets', 'verbose_name_plural': 'Imported Datasets'},
        ),
        migrations.AlterField(
            model_name='results',
            name='Hospitalised_flag',
            field=models.BooleanField(blank=True, help_text='Point estimate includes hospitalised patients', null=True, verbose_name='Hospitalised'),
        ),
        migrations.AlterField(
            model_name='results',
            name='Indigenous_status',
            field=models.BooleanField(blank=True, help_text='Flag indicating whether the measure includes an Indigenous population', null=True, verbose_name='Indigenous'),
        ),
        migrations.AlterField(
            model_name='results',
            name='Interpolated_from_graph',
            field=models.BooleanField(blank=True, help_text='Indicator variable which is “Yes” if point estimate is interpolated and “No” if a numeric figure is given in the publication.', verbose_name='Interpolated'),
        ),
        migrations.AlterField(
            model_name='results',
            name='Schoolchildren_flag',
            field=models.BooleanField(blank=True, help_text='Point estimate includes data of school children', null=True, verbose_name='Schoolchildren'),
        ),
        migrations.AlterField(
            model_name='results',
            name='Study',
            field=models.ForeignKey(default=0, help_text='Select or add the study where these results were published.', on_delete=django.db.models.deletion.CASCADE, to='database.studies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studies',
            name='Surveillance_setting',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Community', 'Community'), ('Hospital', 'Hospital'), ('Household', 'Household'), ('Laboratory', 'Laboratory'), ('Multiple', 'Multiple'), ('Primary health centre', 'Primary health centre'), ('Schools', 'Schools'), ('Other', 'Other')], help_text='The type of institution where the study was conducted. Classifications include primary health care clinic (PHC), tertiary hospital, outpatient clinics, school clinics, households, early childhood centers, aged care facilities etc.', max_length=25, verbose_name='Surveillance setting'),
        ),
    ]
