# Generated by Django 4.1.2 on 2023-04-27 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0007_delete_results_delete_results_pending_delete_studies_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Request_type",
                    models.CharField(
                        choices=[
                            ("addition", "Add a new study"),
                            ("correction", "Make a correction to existing data"),
                            ("other", "Other - please provide details"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "First_author",
                    models.CharField(
                        help_text="Please enter the first author of the study",
                        max_length=100,
                    ),
                ),
                (
                    "Year",
                    models.CharField(
                        help_text="Please enter the publication year of the study",
                        max_length=100,
                        verbose_name="Year of study",
                    ),
                ),
                (
                    "Journal_link",
                    models.CharField(
                        max_length=300, verbose_name="Link to journal article"
                    ),
                ),
                (
                    "Details",
                    models.TextField(
                        blank=True, help_text="Please describe your request"
                    ),
                ),
                ("Created_time", models.DateTimeField(auto_now_add=True)),
                ("Updated_time", models.DateTimeField(auto_now=True)),
                (
                    "Created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request for addition/correction",
                "verbose_name_plural": "Requests for addition/correction",
            },
        ),
        migrations.DeleteModel(
            name="ProxyApprovedResults",
        ),
        migrations.DeleteModel(
            name="ProxyApprovedStudies",
        ),
        migrations.DeleteModel(
            name="ProxyPendingSubmissions",
        ),
        migrations.DeleteModel(
            name="ProxyUserDrafts",
        ),
        migrations.DeleteModel(
            name="ProxyUserSubmissions",
        ),
        migrations.CreateModel(
            name="My_Drafts",
            fields=[],
            options={
                "verbose_name": "Study (Draft)",
                "verbose_name_plural": "Studies (Draft)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("database.studiesmodel",),
        ),
        migrations.CreateModel(
            name="Results",
            fields=[],
            options={
                "verbose_name": "Result",
                "verbose_name_plural": "Results",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("database.resultsmodel",),
        ),
        migrations.CreateModel(
            name="Studies",
            fields=[],
            options={
                "verbose_name": "Study",
                "verbose_name_plural": "Studies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("database.studiesmodel",),
        ),
        migrations.RemoveField(
            model_name="resultsmodel",
            name="Submission_notes",
        ),
        migrations.RemoveField(
            model_name="studiesmodel",
            name="Submission_notes",
        ),
        migrations.AlterField(
            model_name="document",
            name="upload_file",
            field=models.FileField(upload_to="uploads/documents/"),
        ),
        migrations.AlterField(
            model_name="resultsmodel",
            name="Study",
            field=models.ForeignKey(
                help_text="Select or add the study where these results were published.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="database.studiesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="resultsmodel",
            name="Submission_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending admin review"),
                    ("needs_review", "Needs further review"),
                    ("approved", "Approved"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studiesmodel",
            name="Submission_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending admin review"),
                    ("needs_review", "Needs further review"),
                    ("approved", "Approved"),
                ],
                max_length=20,
            ),
        ),
    ]
